---
driver:
  name: ec2 # https://github.com/ansible-community/molecule-plugins/tree/main/doc/ec2
platforms: 
  - name: bigip
    region: us-east-2
    image: ami-0e6d5be8d438c6333 # F5 BIGIP-14.1.5.6-0.12.6 PAYG-Good 25Mbps
    instance_type: m5.xlarge
    vpc_id: vpc-0593d4a257abbede6
    vpc_subnet_id: subnet-01be05574e5a42bdd
    assign_public_ip: true
    key_inject_method: ec2
    boot_wait_seconds: 120
    security_group_name: f5-test
    security_group_rules:
      - proto: tcp
        ports: 8443
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        ports: 22
        cidr_ip: "0.0.0.0/0"
    connection_options:
      ansible_user: admin
  - name: web1
    groups:
     - web
    region: us-east-2
    image: ami-0931978297f275f71 # RHEL 9.2
    instance_type: t2.micro
    vpc_id: vpc-0593d4a257abbede6
    vpc_subnet_id: subnet-01be05574e5a42bdd
    assign_public_ip: true
    key_inject_method: ec2
    boot_wait_seconds: 30
    security_group_name: web-test
    security_group_rules:
      - proto: tcp
        ports: 80
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        ports: 22
        cidr_ip: "0.0.0.0/0"
    connection_options:
      ansible_user: ec2-user
  - name: web2
    groups:
     - web
    region: us-east-2
    image: ami-0931978297f275f71 # RHEL 9.2
    instance_type: t2.micro
    vpc_id: vpc-0593d4a257abbede6
    vpc_subnet_id: subnet-01be05574e5a42bdd
    assign_public_ip: true
    key_inject_method: ec2
    boot_wait_seconds: 30
    security_group_name: web-test
    security_group_rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
    connection_options:
      ansible_user: ec2-user
